In [13]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.datasets import make_moons
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.svm import LinearSVR
from sklearn.svm import SVR
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import PolynomialFeatures

In [2]:
iris = datasets.load_iris()
X = iris["data"][:, (2, 3)] # petal length, petal width
y = (iris["target"] == 2).astype(np.float64) # Iris virginica

### SVM for linearly separable data

In [3]:
svm_clf = Pipeline([("scaler", StandardScaler()), ("linear_svc",LinearSVC())])
svm_clf.fit(X,y)

Pipeline(steps=[('scaler', StandardScaler()), ('linear_svc', LinearSVC())])

In [4]:
svm_clf2 = Pipeline([("scaler", StandardScaler()), ("linear_svc",SVC(kernel="linear"))])
svm_clf2.fit(X,y)

Pipeline(steps=[('scaler', StandardScaler()),
                ('linear_svc', SVC(kernel='linear'))])

In [5]:
svm_clf3 = Pipeline([("scaler", StandardScaler()), ("linear_svc",SGDClassifier(loss="hinge"))])
svm_clf3.fit(X,y)

Pipeline(steps=[('scaler', StandardScaler()), ('linear_svc', SGDClassifier())])

In [6]:
svm_clf.predict([[5.5, 1.7]])

array([1.])

In [7]:
svm_clf2.predict([[5.5, 1.7]])

array([1.])

In [8]:
svm_clf3.predict([[5.5, 1.7]])

array([1.])

### Nonlinear SVM Classification 

#### Linear SVM and Polynomial Features 

In [9]:
X, y = make_moons(n_samples=100, noise=0.15)
polynomial_svm_clf = Pipeline([
("poly_features", PolynomialFeatures(degree=3)),
("scaler", StandardScaler()),
("svm_clf", LinearSVC(C=10, loss="hinge"))
])
polynomial_svm_clf.fit(X, y)


C:\Users\Admin\ML_PATH\my_env\lib\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Pipeline(steps=[('poly_features', PolynomialFeatures(degree=3)),
                ('scaler', StandardScaler()),
                ('svm_clf', LinearSVC(C=10, loss='hinge'))])

### Polynomial Kernel

In [10]:
poly_kernel_svc = Pipeline([("scaler", StandardScaler()),("svm_clf", SVC(kernel="poly", degree=3, coef0=1, C=5))])
poly_kernel_svc.fit(X,y)

Pipeline(steps=[('scaler', StandardScaler()),
                ('svm_clf', SVC(C=5, coef0=1, kernel='poly'))])

### Gaussian Radial Basis Function  ( Gaussian RBF kernel)

In [11]:
rbf_kernel_svm_clf = Pipeline([
("scaler", StandardScaler()),
("svm_clf", SVC(kernel="rbf", gamma=5, C=0.001))
])
rbf_kernel_svm_clf.fit(X, y)

Pipeline(steps=[('scaler', StandardScaler()),
                ('svm_clf', SVC(C=0.001, gamma=5))])

### SVM Regression 

In [12]:
svm_reg = LinearSVR(epsilon=1.5)
svm_reg.fit(X,y)

LinearSVR(epsilon=1.5)

In [14]:
svm_poly_reg = SVR(kernel="poly", degree=2, C=100, epsilon=0.1)
svm_poly_reg.fit(X,y)

SVR(C=100, degree=2, kernel='poly')